pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh "./gradlew clean compile"
            }
        }
        stage('Test') {
            steps {
                sh "./gradlew test"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
