pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                ./gradlew clean compile
            }
        }
        stage('Test') {
            steps {
                ./gradlew test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
